---
- hosts: zookeeper03.foo.bar
  become: true
  connection: ssh
  vars:
    - kafkaversion: 2.6.0
    - brokerid: 4
    - zookeeperinfo: zookeeper01.foo.bar:2181,zookeeper02.foo.bar:2181,zookeeper03.foo.bar:2181
    - dir_path: /data/kafka-logs
  roles:
    - common
    - kafka