# prometheus config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'jmx-kafka'
    static_configs:
      - targets:
        - kafka01.foo.bar:7071
        - kafka02.foo.bar:7071
        - kafka03.foo.bar:7071

  - job_name: 'kafka-nodes'
    static_configs:
      - targets:
          - kafka01.foo.bar:9100
          - kafka02.foo.bar:9100
          - kafka03.foo.bar:9100

  - job_name: 'kafka-exporter'
    static_configs:
      - targets:
          - kafka01.foo.bar:9308
          - kafka02.foo.bar:9308
          - kafka03.foo.bar:9308