zookeeperversion: zookeeper-3.5.9
myid: "{{ inventory_hostname | regex_search('(zookeeper0[0-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^zookeeper0', '') }}"
dir_path: /data/zk